name: Mantener Render Vivo

on:
  schedule:
    # Se ejecuta cada 10 minutos
    - cron: '*/10 * * * *'
  # Esto permite ejecutar el script manualmente desde GitHub si lo necesitas
  workflow_dispatch: 

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Hacer ping a la URL de Render
        run: |
          curl -s https://scraper-rentas.onrender.com
          echo "Ping enviado a Render en verguiza"
